ALTER TABLE IF EXISTS public.sipro_detalle_consolidado_registros
    ALTER COLUMN documento TYPE bigint USING documento::bigint;

CREATE TABLE IF NOT EXISTS public.sipro_parametros_columnas_creffsos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_columna character varying(100) NOT NULL,
    orden integer NOT NULL,
    tipo_dato_salida character varying(30) NOT NULL,
    longitud_maxima integer,
    precision_numerica integer,
    escala_numerica integer,
    formato_salida character varying(100),
    origen_dato character varying(30) NOT NULL,
    tabla_origen character varying(150),
    columna_origen character varying(150),
    alias_origen character varying(100),
    valor_constante character varying(255),
    funcion_java character varying(100),
    expresion_sql text,
    parametros_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    obligatorio boolean NOT NULL DEFAULT true,
    permite_nulo boolean NOT NULL DEFAULT true,
    incluir_salida boolean NOT NULL DEFAULT true,
    estado smallint NOT NULL DEFAULT 1,
    descripcion text,
    observaciones text,
    creado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id bigint,
    modificado_por_id bigint,
    CONSTRAINT sipro_parametros_columnas_creffsos_nombre_key UNIQUE (nombre_columna),
    CONSTRAINT sipro_parametros_columnas_creffsos_orden_key UNIQUE (orden),
    CONSTRAINT chk_sipro_parametros_columnas_creffsos_nombre_upper CHECK (nombre_columna = UPPER(nombre_columna)),
    CONSTRAINT chk_sipro_parametros_columnas_creffsos_tipo_dato CHECK (tipo_dato_salida IN ('STRING', 'INTEGER', 'NUMERIC', 'DATE', 'BOOLEAN')),
    CONSTRAINT chk_sipro_parametros_columnas_creffsos_origen CHECK (origen_dato IN ('DIRECTO', 'CONSTANTE', 'REGLA', 'LOOKUP', 'SECUENCIA', 'VACIO')),
    CONSTRAINT chk_sipro_parametros_columnas_creffsos_estado CHECK (estado IN (0, 1)),
    CONSTRAINT chk_sipro_parametros_columnas_creffsos_longitud CHECK (longitud_maxima IS NULL OR longitud_maxima > 0),
    CONSTRAINT chk_sipro_parametros_columnas_creffsos_precision CHECK (precision_numerica IS NULL OR precision_numerica > 0),
    CONSTRAINT chk_sipro_parametros_columnas_creffsos_escala_min CHECK (escala_numerica IS NULL OR escala_numerica >= 0),
    CONSTRAINT chk_sipro_parametros_columnas_creffsos_escala_max CHECK (
        escala_numerica IS NULL
        OR precision_numerica IS NULL
        OR escala_numerica <= precision_numerica
    ),
    CONSTRAINT fk_sipro_parametros_columnas_creffsos_creado_por FOREIGN KEY (creado_por_id)
        REFERENCES public.usuario_persona(id_usuario),
    CONSTRAINT fk_sipro_parametros_columnas_creffsos_modificado_por FOREIGN KEY (modificado_por_id)
        REFERENCES public.usuario_persona(id_usuario)
);

CREATE INDEX IF NOT EXISTS idx_sipro_parametros_columnas_creffsos_activas
    ON public.sipro_parametros_columnas_creffsos (orden)
    WHERE estado = 1 AND incluir_salida = true;

CREATE INDEX IF NOT EXISTS idx_sipro_parametros_columnas_creffsos_funcion_java
    ON public.sipro_parametros_columnas_creffsos (funcion_java)
    WHERE funcion_java IS NOT NULL;

COMMENT ON TABLE public.sipro_parametros_columnas_creffsos IS
    'Configuración detallada de columnas de salida del archivo CREFFSOS para generación parametrizada desde Java.';

COMMENT ON COLUMN public.sipro_parametros_columnas_creffsos.funcion_java IS
    'Nombre de la estrategia o método Java/Spring que interpreta la regla de negocio de la columna.';

COMMENT ON COLUMN public.sipro_parametros_columnas_creffsos.parametros_json IS
    'Parámetros estructurados para la estrategia Java; evita códigos duros y facilita agregar o quitar columnas.';

INSERT INTO public.sipro_parametros_columnas_creffsos (
    nombre_columna,
    orden,
    tipo_dato_salida,
    longitud_maxima,
    precision_numerica,
    escala_numerica,
    formato_salida,
    origen_dato,
    tabla_origen,
    columna_origen,
    alias_origen,
    valor_constante,
    funcion_java,
    expresion_sql,
    parametros_json,
    obligatorio,
    permite_nulo,
    incluir_salida,
    estado,
    descripcion,
    observaciones
) VALUES
    ('NIT', 1, 'INTEGER', 20, NULL, NULL, '0', 'DIRECTO', 'sipro_detalle_consolidado_registros', 'nit', 'base', NULL, 'copiarDirecto', 'base.nit', jsonb_build_object('sourceField', 'nit'), true, true, true, 1, 'NIT del registro consolidado.', 'Base principal: public.sipro_detalle_consolidado_registros.'),
    ('OFICINA', 2, 'INTEGER', 10, NULL, NULL, '0', 'DIRECTO', 'sipro_detalle_consolidado_registros', 'oficina', 'base', NULL, 'copiarDirecto', 'base.oficina', jsonb_build_object('sourceField', 'oficina'), true, true, true, 1, 'Oficina del registro consolidado.', 'Base principal: public.sipro_detalle_consolidado_registros.'),
    ('GTECUENTA', 3, 'INTEGER', 10, NULL, NULL, '0', 'REGLA', 'sipro_detalle_consolidado_registros', 'oficina', 'base', NULL, 'copiarMismoValorSiInformado', 'CASE WHEN base.oficina IS NULL THEN NULL ELSE base.oficina END', jsonb_build_object('dependsOnSource', 'oficina', 'when', 'NOT_NULL', 'copyFromSource', 'oficina'), true, true, true, 1, 'Replica OFICINA cuando el campo viene informado.', 'Regla funcional Campo 3 de CREFFSOS.'),
    ('ZONA', 4, 'INTEGER', 5, NULL, NULL, '0', 'REGLA', 'sipro_detalle_consolidado_registros', 'oficina', 'base', '1', 'asignarConstanteSiCampoInformado', 'CASE WHEN base.oficina IS NULL THEN NULL ELSE 1 END', jsonb_build_object('dependsOnSource', 'oficina', 'when', 'NOT_NULL', 'valueIfTrue', '1'), true, true, true, 1, 'Asigna 1 cuando OFICINA está informado.', 'Regla funcional Campo 4 de CREFFSOS.'),
    ('DOCUMENTO', 5, 'INTEGER', 20, NULL, NULL, '0', 'SECUENCIA', 'sipro_detalle_consolidado_registros', 'documento', 'base', NULL, 'resolverDocumentoConsecutivo', NULL, jsonb_build_object('sourceField', 'documento', 'useSequenceWhenNullOrZero', true, 'currentSequenceParam', 'CREFFSOS_DOCUMENTO_CONSECUTIVO_ACTUAL', 'initialSequenceParam', 'CREFFSOS_DOCUMENTO_CONSECUTIVO_INICIAL', 'increment', 1), true, true, true, 1, 'Usa DOCUMENTO del origen y genera consecutivo si viene vacío o en cero.', 'El consecutivo queda externalizado en sipro_parametros_unico.'),
    ('MONEDA', 6, 'INTEGER', 10, NULL, NULL, '0', 'DIRECTO', 'sipro_detalle_consolidado_registros', 'moneda', 'base', NULL, 'copiarDirecto', 'base.moneda', jsonb_build_object('sourceField', 'moneda'), true, true, true, 1, 'Moneda del registro consolidado.', 'Base principal: public.sipro_detalle_consolidado_registros.'),
    ('MODALIDAD', 7, 'STRING', 255, NULL, NULL, '@', 'DIRECTO', 'sipro_detalle_consolidado_registros', 'modalidad', 'base', NULL, 'copiarDirecto', 'base.modalidad', jsonb_build_object('sourceField', 'modalidad'), true, true, true, 1, 'Modalidad del registro consolidado.', 'Base principal: public.sipro_detalle_consolidado_registros.'),
    ('ESTADOCR', 8, 'INTEGER', 5, NULL, NULL, '0', 'REGLA', 'sipro_detalle_consolidado_registros', 'modalidad', 'base', '0', 'asignarConstanteSiCampoInformado', 'CASE WHEN base.modalidad IS NULL OR base.modalidad = '''' THEN NULL ELSE 0 END', jsonb_build_object('dependsOnSource', 'modalidad', 'when', 'NOT_BLANK', 'valueIfTrue', '0'), true, true, true, 1, 'Asigna 0 cuando MODALIDAD tiene valor.', 'Regla funcional Campo 8 de CREFFSOS.'),
    ('ANOINIOBL', 9, 'INTEGER', 4, NULL, NULL, '0', 'DIRECTO', 'sipro_detalle_consolidado_registros', 'anoiniobl', 'base', NULL, 'copiarDirecto', 'base.anoiniobl', jsonb_build_object('sourceField', 'anoiniobl'), true, true, true, 1, 'Año inicial de obligación.', 'Base principal: public.sipro_detalle_consolidado_registros.'),
    ('MESINIOBL', 10, 'INTEGER', 2, NULL, NULL, '0', 'DIRECTO', 'sipro_detalle_consolidado_registros', 'mesiniobl', 'base', NULL, 'copiarDirecto', 'base.mesiniobl', jsonb_build_object('sourceField', 'mesiniobl'), true, true, true, 1, 'Mes inicial de obligación.', 'Base principal: public.sipro_detalle_consolidado_registros.'),
    ('DIAINIOBL', 11, 'INTEGER', 2, NULL, NULL, '0', 'DIRECTO', 'sipro_detalle_consolidado_registros', 'diainiobl', 'base', NULL, 'copiarDirecto', 'base.diainiobl', jsonb_build_object('sourceField', 'diainiobl'), true, true, true, 1, 'Día inicial de obligación.', 'Base principal: public.sipro_detalle_consolidado_registros.'),
    ('ANOVCTO', 12, 'INTEGER', 4, NULL, NULL, '0', 'DIRECTO', 'sipro_detalle_consolidado_registros', 'anovcto', 'base', NULL, 'copiarDirecto', 'base.anovcto', jsonb_build_object('sourceField', 'anovcto'), true, true, true, 1, 'Año de vencimiento.', 'Base principal: public.sipro_detalle_consolidado_registros.'),
    ('MESVCTO', 13, 'INTEGER', 2, NULL, NULL, '0', 'DIRECTO', 'sipro_detalle_consolidado_registros', 'mesvcto', 'base', NULL, 'copiarDirecto', 'base.mesvcto', jsonb_build_object('sourceField', 'mesvcto'), true, true, true, 1, 'Mes de vencimiento.', 'Base principal: public.sipro_detalle_consolidado_registros.'),
    ('DIAVCTO', 14, 'INTEGER', 2, NULL, NULL, '0', 'DIRECTO', 'sipro_detalle_consolidado_registros', 'diavcto', 'base', NULL, 'copiarDirecto', 'base.diavcto', jsonb_build_object('sourceField', 'diavcto'), true, true, true, 1, 'Día de vencimiento.', 'Base principal: public.sipro_detalle_consolidado_registros.'),
    ('ANOVCTOFIN', 15, 'INTEGER', 4, NULL, NULL, '0', 'DIRECTO', 'sipro_detalle_consolidado_registros', 'anovctofin', 'base', NULL, 'copiarDirecto', 'base.anovctofin', jsonb_build_object('sourceField', 'anovctofin'), true, true, true, 1, 'Año de vencimiento final.', 'Base principal: public.sipro_detalle_consolidado_registros.'),
    ('MESVCTOFIN', 16, 'INTEGER', 2, NULL, NULL, '0', 'DIRECTO', 'sipro_detalle_consolidado_registros', 'mesvctofin', 'base', NULL, 'copiarDirecto', 'base.mesvctofin', jsonb_build_object('sourceField', 'mesvctofin'), true, true, true, 1, 'Mes de vencimiento final.', 'Base principal: public.sipro_detalle_consolidado_registros.'),
    ('DIAVCTOFIN', 17, 'INTEGER', 2, NULL, NULL, '0', 'DIRECTO', 'sipro_detalle_consolidado_registros', 'diavctofin', 'base', NULL, 'copiarDirecto', 'base.diavctofin', jsonb_build_object('sourceField', 'diavctofin'), true, true, true, 1, 'Día de vencimiento final.', 'Base principal: public.sipro_detalle_consolidado_registros.'),
    ('ANOULTPAGO', 18, 'INTEGER', 4, NULL, NULL, '0', 'REGLA', 'sipro_detalle_consolidado_registros', 'diavctofin', 'base', '0', 'asignarConstanteSiCampoInformado', 'CASE WHEN base.diavctofin IS NULL THEN NULL ELSE 0 END', jsonb_build_object('dependsOnSource', 'diavctofin', 'when', 'NOT_NULL', 'valueIfTrue', '0'), true, true, true, 1, 'Año último pago; usa 0 cuando DIAVCTOFIN viene informado.', 'Regla funcional Campo 18 de CREFFSOS.'),
    ('MESULTPAGO', 19, 'INTEGER', 2, NULL, NULL, '0', 'REGLA', 'sipro_detalle_consolidado_registros', 'diavctofin', 'base', '0', 'asignarConstanteSiCampoInformado', 'CASE WHEN base.diavctofin IS NULL THEN NULL ELSE 0 END', jsonb_build_object('dependsOnSource', 'diavctofin', 'when', 'NOT_NULL', 'valueIfTrue', '0'), true, true, true, 1, 'Mes último pago; usa 0 cuando DIAVCTOFIN viene informado.', 'Regla funcional Campo 19 de CREFFSOS.'),
    ('DIAULTPAGO', 20, 'INTEGER', 2, NULL, NULL, '0', 'REGLA', 'sipro_detalle_consolidado_registros', 'diavctofin', 'base', '0', 'asignarConstanteSiCampoInformado', 'CASE WHEN base.diavctofin IS NULL THEN NULL ELSE 0 END', jsonb_build_object('dependsOnSource', 'diavctofin', 'when', 'NOT_NULL', 'valueIfTrue', '0'), true, true, true, 1, 'Día último pago; usa 0 cuando DIAVCTOFIN viene informado.', 'Regla funcional Campo 20 de CREFFSOS.'),
    ('TASAINTVIG', 21, 'INTEGER', 10, NULL, NULL, '0', 'REGLA', 'sipro_detalle_consolidado_registros', 'diavctofin', 'base', '0', 'asignarConstanteSiCampoInformado', 'CASE WHEN base.diavctofin IS NULL THEN NULL ELSE 0 END', jsonb_build_object('dependsOnSource', 'diavctofin', 'when', 'NOT_NULL', 'valueIfTrue', '0'), true, true, true, 1, 'Tasa interés vigente; usa 0 cuando DIAVCTOFIN viene informado.', 'Regla funcional Campo 21 de CREFFSOS.'),
    ('TASAINTMRA', 22, 'INTEGER', 10, NULL, NULL, '0', 'REGLA', 'sipro_detalle_consolidado_registros', 'diavctofin', 'base', '0', 'asignarConstanteSiCampoInformado', 'CASE WHEN base.diavctofin IS NULL THEN NULL ELSE 0 END', jsonb_build_object('dependsOnSource', 'diavctofin', 'when', 'NOT_NULL', 'valueIfTrue', '0'), true, true, true, 1, 'Tasa interés mora; usa 0 cuando DIAVCTOFIN viene informado.', 'Regla funcional Campo 22 de CREFFSOS.'),
    ('TASAREDESC', 23, 'INTEGER', 10, NULL, NULL, '0', 'REGLA', 'sipro_detalle_consolidado_registros', 'diavctofin', 'base', '0', 'asignarConstanteSiCampoInformado', 'CASE WHEN base.diavctofin IS NULL THEN NULL ELSE 0 END', jsonb_build_object('dependsOnSource', 'diavctofin', 'when', 'NOT_NULL', 'valueIfTrue', '0'), true, true, true, 1, 'Tasa redescuento; usa 0 cuando DIAVCTOFIN viene informado.', 'Regla funcional Campo 23 de CREFFSOS.'),
    ('PORCRDSCTO', 24, 'INTEGER', 10, NULL, NULL, '0', 'REGLA', 'sipro_detalle_consolidado_registros', 'diavctofin', 'base', '0', 'asignarConstanteSiCampoInformado', 'CASE WHEN base.diavctofin IS NULL THEN NULL ELSE 0 END', jsonb_build_object('dependsOnSource', 'diavctofin', 'when', 'NOT_NULL', 'valueIfTrue', '0'), true, true, true, 1, 'Porcentaje redescuento; usa 0 cuando DIAVCTOFIN viene informado.', 'Regla funcional Campo 24 de CREFFSOS.'),
    ('CTAPUC', 25, 'INTEGER', 20, NULL, NULL, '0', 'LOOKUP', 'sipro_detalle_consolidado_registros', 'ctapuc', 'base', NULL, 'resolverCuentaBankvision', NULL, jsonb_build_object('sourceField', 'ctapuc', 'lookupTable', 'public.sipro_parametros_homologacion_colgaap', 'lookupKey', 'cuenta_sap', 'lookupValue', 'cuenta_bv', 'ifNotFound', 'NULL'), true, true, true, 1, 'Cuenta PUC homologada hacia Bankvision.', 'Cruza CTAPUC con public.sipro_parametros_homologacion_colgaap.cuenta_sap para traer cuenta_bv.'),
    ('CLASETASA', 26, 'STRING', 3, NULL, NULL, '@', 'CONSTANTE', NULL, NULL, NULL, '   ', 'asignarConstante', '''   ''', jsonb_build_object('value', '   '), true, true, true, 1, 'Tres espacios en blanco según especificación funcional.', 'Regla funcional Campo 26 de CREFFSOS.'),
    ('VLRINIOBL', 27, 'NUMERIC', NULL, 18, 2, '0.00', 'DIRECTO', 'sipro_detalle_consolidado_registros', 'vlriniobl', 'base', NULL, 'copiarDirecto', 'base.vlriniobl', jsonb_build_object('sourceField', 'vlriniobl'), true, true, true, 1, 'Valor inicial de la obligación.', 'Base principal: public.sipro_detalle_consolidado_registros.'),
    ('SALDO', 28, 'NUMERIC', NULL, 18, 2, '0.00', 'DIRECTO', 'sipro_detalle_consolidado_registros', 'saldo', 'base', NULL, 'copiarDirecto', 'base.saldo', jsonb_build_object('sourceField', 'saldo'), true, true, true, 1, 'Saldo del registro consolidado.', 'Base principal: public.sipro_detalle_consolidado_registros.'),
    ('SDOOTRCTAS', 29, 'NUMERIC', NULL, 18, 2, '0.00', 'DIRECTO', 'sipro_detalle_consolidado_registros', 'sdootrctas', 'base', NULL, 'copiarDirecto', 'base.sdootrctas', jsonb_build_object('sourceField', 'sdootrctas'), true, true, true, 1, 'Saldo otras cuentas.', 'Base principal: public.sipro_detalle_consolidado_registros.'),
    ('INTERESES', 30, 'NUMERIC', NULL, 18, 2, '0.00', 'DIRECTO', 'sipro_detalle_consolidado_registros', 'intereses', 'base', NULL, 'copiarDirecto', 'base.intereses', jsonb_build_object('sourceField', 'intereses'), true, true, true, 1, 'Intereses del registro consolidado.', 'Base principal: public.sipro_detalle_consolidado_registros.'),
    ('SDOVENCIDO', 31, 'NUMERIC', NULL, 18, 2, '0.00', 'DIRECTO', 'sipro_detalle_consolidado_registros', 'sdovencido', 'base', NULL, 'copiarDirecto', 'base.sdovencido', jsonb_build_object('sourceField', 'sdovencido'), true, true, true, 1, 'Saldo vencido.', 'Base principal: public.sipro_detalle_consolidado_registros.'),
    ('INTCTASORD', 32, 'NUMERIC', NULL, 18, 2, '0.00', 'DIRECTO', 'sipro_detalle_consolidado_registros', 'intctasord', 'base', NULL, 'copiarDirecto', 'base.intctasord', jsonb_build_object('sourceField', 'intctasord'), true, true, true, 1, 'Intereses cuentas orden.', 'Base principal: public.sipro_detalle_consolidado_registros.'),
    ('SALDOMES', 33, 'INTEGER', 10, NULL, NULL, '0', 'REGLA', 'sipro_detalle_consolidado_registros', 'diavctofin', 'base', '0', 'asignarConstanteSiCampoInformado', 'CASE WHEN base.diavctofin IS NULL THEN NULL ELSE 0 END', jsonb_build_object('dependsOnSource', 'diavctofin', 'when', 'NOT_NULL', 'valueIfTrue', '0'), true, true, true, 1, 'Saldo mes; usa 0 cuando DIAVCTOFIN viene informado.', 'Regla funcional Campo 33 de CREFFSOS.'),
    ('PROVCAPANT', 34, 'INTEGER', 10, NULL, NULL, '0', 'REGLA', NULL, NULL, NULL, '0', 'asignarCeroSiSalidaInformada', NULL, jsonb_build_object('dependsOnOutput', 'SALDOMES', 'when', 'NOT_NULL', 'valueIfTrue', '0'), true, true, true, 1, 'Provisión capital anterior; depende de SALDOMES.', 'Regla encadenada por salida generada.'),
    ('PROVCAPACT', 35, 'INTEGER', 10, NULL, NULL, '0', 'REGLA', NULL, NULL, NULL, '0', 'asignarCeroSiSalidaInformada', NULL, jsonb_build_object('dependsOnOutput', 'PROVCAPANT', 'when', 'NOT_NULL', 'valueIfTrue', '0'), true, true, true, 1, 'Provisión capital actual; depende de PROVCAPANT.', 'Regla encadenada por salida generada.'),
    ('PROVINTANT', 36, 'INTEGER', 10, NULL, NULL, '0', 'REGLA', NULL, NULL, NULL, '0', 'asignarCeroSiSalidaInformada', NULL, jsonb_build_object('dependsOnOutput', 'PROVCAPACT', 'when', 'NOT_NULL', 'valueIfTrue', '0'), true, true, true, 1, 'Provisión interés anterior; depende de PROVCAPACT.', 'Regla encadenada por salida generada.'),
    ('PROVINTACT', 37, 'INTEGER', 10, NULL, NULL, '0', 'REGLA', NULL, NULL, NULL, '0', 'asignarCeroSiSalidaInformada', NULL, jsonb_build_object('dependsOnOutput', 'PROVINTANT', 'when', 'NOT_NULL', 'valueIfTrue', '0'), true, true, true, 1, 'Provisión interés actual; depende de PROVINTANT.', 'Regla encadenada por salida generada.'),
    ('PROVOTRANT', 38, 'INTEGER', 10, NULL, NULL, '0', 'REGLA', NULL, NULL, NULL, '0', 'asignarCeroSiSalidaInformada', NULL, jsonb_build_object('dependsOnOutput', 'PROVINTACT', 'when', 'NOT_NULL', 'valueIfTrue', '0'), true, true, true, 1, 'Provisión otras anterior; depende de PROVINTACT.', 'Regla encadenada por salida generada.'),
    ('PROVOTRACT', 39, 'INTEGER', 10, NULL, NULL, '0', 'REGLA', NULL, NULL, NULL, '0', 'asignarCeroSiSalidaInformada', NULL, jsonb_build_object('dependsOnOutput', 'PROVOTRANT', 'when', 'NOT_NULL', 'valueIfTrue', '0'), true, true, true, 1, 'Provisión otras actual; depende de PROVOTRANT.', 'Regla encadenada por salida generada.'),
    ('PROVCAPUSA', 40, 'INTEGER', 10, NULL, NULL, '0', 'REGLA', NULL, NULL, NULL, '0', 'asignarCeroSiSalidaInformada', NULL, jsonb_build_object('dependsOnOutput', 'PROVOTRACT', 'when', 'NOT_NULL', 'valueIfTrue', '0'), true, true, true, 1, 'Provisión capital USA; depende de PROVOTRACT.', 'Regla encadenada por salida generada.'),
    ('PROVINTUSA', 41, 'INTEGER', 10, NULL, NULL, '0', 'REGLA', NULL, NULL, NULL, '0', 'asignarCeroSiSalidaInformada', NULL, jsonb_build_object('dependsOnOutput', 'PROVCAPUSA', 'when', 'NOT_NULL', 'valueIfTrue', '0'), true, true, true, 1, 'Provisión interés USA; depende de PROVCAPUSA.', 'Regla encadenada por salida generada.'),
    ('GARANTIA', 42, 'INTEGER', 10, NULL, NULL, '0', 'REGLA', NULL, NULL, NULL, '0', 'asignarCeroSiSalidaInformada', NULL, jsonb_build_object('dependsOnOutput', 'PROVINTUSA', 'when', 'NOT_NULL', 'valueIfTrue', '0'), true, true, true, 1, 'Garantía; depende de PROVINTUSA.', 'Regla encadenada por salida generada.'),
    ('GARCREDITO', 43, 'INTEGER', 10, NULL, NULL, '0', 'REGLA', NULL, NULL, NULL, '0', 'asignarCeroSiSalidaInformada', NULL, jsonb_build_object('dependsOnOutput', 'GARANTIA', 'when', 'NOT_NULL', 'valueIfTrue', '0'), true, true, true, 1, 'Garantía crédito; depende de GARANTIA.', 'Regla encadenada por salida generada.'),
    ('CLASEGTIA', 44, 'STRING', 10, NULL, NULL, '@', 'LOOKUP', 'sipro_detalle_consolidado_registros', 'documento', 'base', 'N', 'resolverClaseGarantiaDesdeCenie', NULL, jsonb_build_object('sourceField', 'documento', 'lookupSystem', 'IMPALA', 'lookupSchema', 's_productos', 'lookupTable', 'bvnc_visionry_cenie', 'lookupKey', 'ceac21', 'lookupValue', 'cein21', 'filters', jsonb_build_object('cest21NotIn', jsonb_build_array('01', '02'), 'cetr21', 1, 'ceap21Trim', 'C', 'ultimaFechaIngestion', true), 'defaultValue', 'N'), true, true, true, 1, 'Clase de garantía consultada en CENIE.', 'Requiere integración con Impala/LZ para la consulta externa.'),
    ('DSTECONOM', 45, 'STRING', 10, NULL, NULL, '@', 'REGLA', NULL, NULL, NULL, '000260', 'asignarConstanteSiSalidaInformada', NULL, jsonb_build_object('dependsOnOutput', 'CLASEGTIA', 'when', 'NOT_NULL', 'valueIfTrue', '000260'), true, true, true, 1, 'Destino económico; usa 000260 cuando CLASEGTIA tiene valor.', 'Regla funcional Campo 45 de CREFFSOS.'),
    ('CLASIFCPUC', 46, 'INTEGER', 5, NULL, NULL, '0', 'REGLA', 'sipro_detalle_consolidado_registros', NULL, 'base', NULL, 'resolverClasificacionCpuc', 'CASE WHEN base.modalidad = ''HIP'' THEN 3 WHEN base.tipo_id IN (''FS003'', ''FS007'', ''FS008'') THEN 1 WHEN base.modalidad = ''DSC'' THEN 1 ELSE 2 END', jsonb_build_object('sourceFields', jsonb_build_array('modalidad', 'tipo_id'), 'modalidadHip', 'HIP', 'modalidadDsc', 'DSC', 'tiposClasificacionUno', jsonb_build_array('FS003', 'FS007', 'FS008'), 'defaultValue', 2), true, true, true, 1, 'Clasificación PUC según modalidad y tipo de identificación.', 'Regla funcional Campo 46 de CREFFSOS.'),
    ('CLASIFCUSA', 47, 'INTEGER', 5, NULL, NULL, '0', 'REGLA', NULL, NULL, NULL, NULL, 'copiarSalidaSiInformada', NULL, jsonb_build_object('dependsOnOutput', 'CLASIFCPUC', 'when', 'NOT_NULL', 'copyFromOutput', 'CLASIFCPUC'), true, true, true, 1, 'Clasificación CUSA; replica CLASIFCPUC cuando existe.', 'Se parametriza así por la ambigüedad del documento funcional.'),
    ('CALIFICPUC', 48, 'STRING', 10, NULL, NULL, '@', 'LOOKUP', 'sipro_detalle_consolidado_registros', 'documento', 'base', 'A', 'resolverCalificacionDesdeCenie', NULL, jsonb_build_object('sourceField', 'documento', 'lookupSystem', 'IMPALA', 'lookupSchema', 's_productos', 'lookupTable', 'bvnc_visionry_cenie', 'lookupKey', 'ceac21', 'lookupValue', 'ceca21', 'filters', jsonb_build_object('cest21NotIn', jsonb_build_array('01', '02'), 'cetr21', 1, 'ceap21Trim', 'C', 'ultimaFechaIngestion', true), 'defaultValue', 'A'), true, true, true, 1, 'Calificación PUC consultada en CENIE.', 'Requiere integración con Impala/LZ para la consulta externa.'),
    ('CALIFICUSA', 49, 'STRING', 10, NULL, NULL, '@', 'VACIO', NULL, NULL, NULL, NULL, 'dejarVacio', 'NULL', jsonb_build_object(), true, true, true, 1, 'Campo vacío según especificación funcional.', 'Regla funcional Campo 49 de CREFFSOS.'),
    ('PLAZO', 50, 'INTEGER', 10, NULL, NULL, '0', 'REGLA', NULL, NULL, NULL, '0', 'asignarCeroSiSalidaInformada', NULL, jsonb_build_object('dependsOnOutput', 'CTAPUC', 'when', 'NOT_NULL', 'valueIfTrue', '0'), true, true, true, 1, 'Plazo; usa 0 cuando CTAPUC está informado.', 'Regla funcional Campo 50 de CREFFSOS.'),
    ('VALORUSU1', 51, 'INTEGER', 10, NULL, NULL, '0', 'REGLA', NULL, NULL, NULL, '0', 'asignarCeroSiSalidaInformada', NULL, jsonb_build_object('dependsOnOutput', 'PLAZO', 'when', 'NOT_NULL', 'valueIfTrue', '0'), true, true, true, 1, 'Valor usuario 1; depende de PLAZO.', 'Regla encadenada por salida generada.'),
    ('VALORUSU2', 52, 'INTEGER', 10, NULL, NULL, '0', 'REGLA', NULL, NULL, NULL, '0', 'asignarCeroSiSalidaInformada', NULL, jsonb_build_object('dependsOnOutput', 'VALORUSU1', 'when', 'NOT_NULL', 'valueIfTrue', '0'), true, true, true, 1, 'Valor usuario 2; depende de VALORUSU1.', 'Regla encadenada por salida generada.'),
    ('VALORUSU3', 53, 'INTEGER', 10, NULL, NULL, '0', 'REGLA', NULL, NULL, NULL, '0', 'asignarCeroSiSalidaInformada', NULL, jsonb_build_object('dependsOnOutput', 'VALORUSU2', 'when', 'NOT_NULL', 'valueIfTrue', '0'), true, true, true, 1, 'Valor usuario 3; depende de VALORUSU2.', 'Regla encadenada por salida generada.'),
    ('VALORUSU4', 54, 'INTEGER', 10, NULL, NULL, '0', 'REGLA', NULL, NULL, NULL, '0', 'asignarCeroSiSalidaInformada', NULL, jsonb_build_object('dependsOnOutput', 'VALORUSU3', 'when', 'NOT_NULL', 'valueIfTrue', '0'), true, true, true, 1, 'Valor usuario 4; depende de VALORUSU3.', 'Regla encadenada por salida generada.'),
    ('FECHAUSU1', 55, 'INTEGER', 10, NULL, NULL, '0', 'REGLA', NULL, NULL, NULL, '0', 'asignarCeroSiSalidaInformada', NULL, jsonb_build_object('dependsOnOutput', 'VALORUSU4', 'when', 'NOT_NULL', 'valueIfTrue', '0'), true, true, true, 1, 'Fecha usuario 1; depende de VALORUSU4.', 'Regla encadenada por salida generada.'),
    ('FECHAUSU2', 56, 'INTEGER', 10, NULL, NULL, '0', 'REGLA', NULL, NULL, NULL, '0', 'asignarCeroSiSalidaInformada', NULL, jsonb_build_object('dependsOnOutput', 'FECHAUSU1', 'when', 'NOT_NULL', 'valueIfTrue', '0'), true, true, true, 1, 'Fecha usuario 2; depende de FECHAUSU1.', 'Regla encadenada por salida generada.'),
    ('INDICUSU1', 57, 'STRING', 3, NULL, NULL, '@', 'CONSTANTE', NULL, NULL, NULL, '   ', 'asignarConstante', '''   ''', jsonb_build_object('value', '   '), true, true, true, 1, 'Tres espacios en blanco según especificación funcional.', 'Regla funcional Campo 57 de CREFFSOS.'),
    ('INDICUSU2', 58, 'STRING', 3, NULL, NULL, '@', 'CONSTANTE', NULL, NULL, NULL, '   ', 'asignarConstante', '''   ''', jsonb_build_object('value', '   '), true, true, true, 1, 'Tres espacios en blanco según especificación funcional.', 'Regla funcional Campo 58 de CREFFSOS.'),
    ('INDICUSU3', 59, 'INTEGER', 10, NULL, NULL, '0', 'REGLA', NULL, NULL, NULL, '0', 'asignarCeroSiSalidaInformada', NULL, jsonb_build_object('dependsOnOutput', 'CTAPUC', 'when', 'NOT_NULL', 'valueIfTrue', '0'), true, true, true, 1, 'Indicador usuario 3; depende de CTAPUC.', 'Regla funcional Campo 59 de CREFFSOS.'),
    ('INDICUSU4', 60, 'INTEGER', 10, NULL, NULL, '0', 'REGLA', NULL, NULL, NULL, '0', 'asignarCeroSiSalidaInformada', NULL, jsonb_build_object('dependsOnOutput', 'INDICUSU3', 'when', 'NOT_NULL', 'valueIfTrue', '0'), true, true, true, 1, 'Indicador usuario 4; depende de INDICUSU3.', 'Regla encadenada por salida generada.'),
    ('TASAUSU1', 61, 'INTEGER', 10, NULL, NULL, '0', 'REGLA', NULL, NULL, NULL, '0', 'asignarCeroSiSalidaInformada', NULL, jsonb_build_object('dependsOnOutput', 'INDICUSU4', 'when', 'NOT_NULL', 'valueIfTrue', '0'), true, true, true, 1, 'Tasa usuario 1; depende de INDICUSU4.', 'Regla encadenada por salida generada.')
ON CONFLICT (nombre_columna) DO UPDATE
SET
    orden = EXCLUDED.orden,
    tipo_dato_salida = EXCLUDED.tipo_dato_salida,
    longitud_maxima = EXCLUDED.longitud_maxima,
    precision_numerica = EXCLUDED.precision_numerica,
    escala_numerica = EXCLUDED.escala_numerica,
    formato_salida = EXCLUDED.formato_salida,
    origen_dato = EXCLUDED.origen_dato,
    tabla_origen = EXCLUDED.tabla_origen,
    columna_origen = EXCLUDED.columna_origen,
    alias_origen = EXCLUDED.alias_origen,
    valor_constante = EXCLUDED.valor_constante,
    funcion_java = EXCLUDED.funcion_java,
    expresion_sql = EXCLUDED.expresion_sql,
    parametros_json = EXCLUDED.parametros_json,
    obligatorio = EXCLUDED.obligatorio,
    permite_nulo = EXCLUDED.permite_nulo,
    incluir_salida = EXCLUDED.incluir_salida,
    estado = EXCLUDED.estado,
    descripcion = EXCLUDED.descripcion,
    observaciones = EXCLUDED.observaciones,
    modificado_en = CURRENT_TIMESTAMP;

INSERT INTO public.sipro_parametros_columnas (
    categoria,
    nombre_columna,
    orden,
    descripcion,
    estado
)
SELECT
    'CREFFSOS' AS categoria,
    nombre_columna,
    orden,
    LEFT(COALESCE(descripcion, ''), 255) AS descripcion,
    estado
FROM public.sipro_parametros_columnas_creffsos
ON CONFLICT (categoria, nombre_columna) DO UPDATE
SET
    orden = EXCLUDED.orden,
    descripcion = EXCLUDED.descripcion,
    estado = EXCLUDED.estado;

WITH max_documento AS (
    SELECT COALESCE(MAX(documento), 0)::character varying AS valor
    FROM public.sipro_detalle_consolidado_registros
    WHERE documento IS NOT NULL AND documento > 0
), parametros AS (
    SELECT
        'CREFFSOS_RUTA_SALIDA'::character varying AS clave,
        $$\\sbmdebns03\CornerStone\componentes\DIR SERV EMPRESA Y GBNO\GCIA CARTERA EMPRESA Y GBNO$$::character varying AS valor,
        'STRING'::character varying AS tipo,
        'Ruta compartida donde debe publicarse el consolidado CREFFSOS.'::text AS descripcion
    UNION ALL
    SELECT 'CREFFSOS_NOMBRE_ARCHIVO_SALIDA', 'CREFFSOS.csv', 'STRING', 'Nombre del archivo final a generar para CREFFSOS.'
    UNION ALL
    SELECT 'CREFFSOS_FORMATO_SALIDA', 'CSV', 'STRING', 'Formato de salida actual del consolidado CREFFSOS; permite cambiar a CSV, TSV o XLSX sin rediseñar la tabla.'
    UNION ALL
    SELECT 'CREFFSOS_HOJA_XLSX', 'CREFFSOS', 'STRING', 'Nombre de la hoja de trabajo al exportar el consolidado CREFFSOS a Excel.'
    UNION ALL
    SELECT 'CREFFSOS_INCLUIR_ENCABEZADO', 'false', 'BOOLEAN', 'Indica si el archivo final generado debe incluir fila de encabezado.'
    UNION ALL
    SELECT 'CREFFSOS_DOCUMENTO_CONSECUTIVO_INICIAL', valor, 'INTEGER', 'Valor base inicial para la secuencia de DOCUMENTO cuando el origen no traiga dato.'
    FROM max_documento
    UNION ALL
    SELECT 'CREFFSOS_DOCUMENTO_CONSECUTIVO_ACTUAL', valor, 'INTEGER', 'Último consecutivo utilizado para la regla de DOCUMENTO cuando el origen no traiga dato.'
    FROM max_documento
)
INSERT INTO public.sipro_parametros_unico (
    clave,
    valor,
    tipo,
    descripcion
)
SELECT
    clave,
    valor,
    tipo,
    descripcion
FROM parametros
ON CONFLICT (clave) DO UPDATE
SET
    valor = EXCLUDED.valor,
    tipo = EXCLUDED.tipo,
    descripcion = EXCLUDED.descripcion,
    modificado_en = CURRENT_TIMESTAMP;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'appuser') THEN
        EXECUTE 'ALTER TABLE public.sipro_parametros_columnas_creffsos OWNER TO appuser';
    END IF;
END $$;